// this is firebase.js with long-polling disabled
var WebSocket = require("lib/websocket").WebSocket; // must provide this
var setTimeout = require("timers").setTimeout;
var clearTimeout = require("timers").clearTimeout;
var setInterval = require("timers").setInterval;
(function() {function g(a){throw a;}var i=void 0,l=!0,m=null,n=!1;function p(){return function(){}}function aa(a){return function(){return this[a]}}function q(a){return function(){return a}}var r,ba=this;function ca(){}
function da(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function t(a){return a!==i}function ea(a){var b=da(a);return"array"==b||"object"==b&&"number"==typeof a.length}function v(a){return"string"==typeof a}function fa(a){return"number"==typeof a}function ga(a){return"function"==da(a)}function ha(a){var b=typeof a;return"object"==b&&a!=m||"function"==b}Math.floor(2147483648*Math.random()).toString(36);function ia(a,b,c){return a.call.apply(a.bind,arguments)}
function ja(a,b,c){a||g(Error());if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function y(a,b,c){y=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ia:ja;return y.apply(m,arguments)}function ka(a,b){function c(){}c.prototype=b.prototype;a.cd=b.prototype;a.prototype=new c};function la(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x10-\x1f\x80-\x9f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}g(Error("Invalid JSON string: "+a))}function ma(){this.Cb=i}
function na(a,b,c){switch(typeof b){case "string":oa(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==m){c.push("null");break}if("array"==da(b)){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),e=b[f],na(a,a.Cb?a.Cb.call(b,String(f),e):e,c),e=",";c.push("]");break}c.push("{");d="";for(f in b)Object.prototype.hasOwnProperty.call(b,f)&&(e=b[f],"function"!=typeof e&&(c.push(d),
oa(f,c),c.push(":"),na(a,a.Cb?a.Cb.call(b,f,e):e,c),d=","));c.push("}");break;case "function":break;default:g(Error("Unknown type: "+typeof b))}}var pa={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},qa=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
function oa(a,b){b.push('"',a.replace(qa,function(a){if(a in pa)return pa[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return pa[a]=e+b.toString(16)}),'"')};function z(a){if("undefined"!==typeof JSON&&t(JSON.stringify))a=JSON.stringify(a);else{var b=[];na(new ma,a,b);a=b.join("")}return a};function A(a,b,c,d){var e;d<b?e="at least "+b:d>c&&(e=0===c?"none":"no more than "+c);e&&g(Error(a+" failed: Was called with "+d+(1===d?" argument.":" arguments.")+" Expects "+e+"."))}function B(a,b,c){var d="";switch(b){case 1:d=c?"first":"First";break;case 2:d=c?"second":"Second";break;case 3:d=c?"third":"Third";break;case 4:d=c?"fourth":"Fourth";break;default:ra.assert(n,"errorPrefix_ called with argumentNumber > 4.  Need to update it?")}return a+" failed: "+(d+" argument ")}
function C(a,b,c,d){(!d||t(c))&&!ga(c)&&g(Error(B(a,b,d)+"must be a valid function."))}function sa(a,b,c){t(c)&&(!ha(c)||c===m)&&g(Error(B(a,b,l)+"must be a valid context object."))};function D(a,b){return Object.prototype.hasOwnProperty.call(a,b)}function ta(a,b){if(Object.prototype.hasOwnProperty.call(a,b))return a[b]};var ua={},ra={},va=/[\[\].#$\/]/,wa=/[\[\].#$]/;function xa(a){return v(a)&&0!==a.length&&!va.test(a)}function ya(a,b,c){(!c||t(b))&&za(B(a,1,c),b)}
function za(a,b,c,d){c||(c=0);d||(d=[]);t(b)||g(Error(a+"contains undefined"+Aa(d)));ga(b)&&g(Error(a+"contains a function"+Aa(d)));Ba(b)&&g(Error(a+"contains "+b.toString()+Aa(d)));1E3<c&&g(new TypeError(a+"contains a cyclic object value ("+d.slice(0,100).join(".")+"...)"));v(b)&&(b.length>10485760/3&&10485760<ua.dd.bd(b).length)&&g(Error(a+"contains a string greater than 10485760 utf8 bytes"+Aa(d)+" ('"+b.substring(0,50)+"...')"));if(ha(b))for(var e in b)D(b,e)&&(".priority"!==e&&(".value"!==e&&
!xa(e))&&g(Error(a+"contains an invalid key ("+e+")"+Aa(d)+'.  Keys must be non-empty strings and can\'t contain ".", "#", "$", "/", "[", or "]"')),d.push(e),za(a,b[e],c+1,d),d.pop())}function Aa(a){return 0==a.length?"":" in property "+a.join(".")}function Ca(a,b,c,d){(!d||t(c))&&(c!==m&&!fa(c)&&!v(c))&&g(Error(B(a,b,d)+"must be a valid firebase priority (null or a string.)"))}
function Da(a,b,c){if(!c||t(b))switch(b){case "value":case "child_added":case "child_removed":case "child_changed":case "child_moved":break;default:g(Error(B(a,1,c)+'must be a valid event type: "value", "child_added", "child_removed", "child_changed", or "child_moved".'))}}function Ea(a,b){t(b)&&!xa(b)&&g(Error(B(a,2,l)+'must be a valid firebase key (non-empty string, not containing ".", "#", "$", "/", "[", or "]").'))}
function Fa(a,b){(!v(b)||0===b.length||wa.test(b))&&g(Error(B(a,1,n)+'must be a non-empty string and can\'t contain ".", "#", "$", "[", or "]".'))}function Ga(a,b){".info"===E(b)&&g(Error(a+" failed: Can't modify data under /.info/"))};function F(a,b,c,d,e,f,h){this.k=a;this.path=b;this.oa=c;this.W=d;this.ga=e;this.la=f;this.Ea=h;t(this.W)&&(t(this.la)&&t(this.oa))&&g("Query: Can't combine startAt(), endAt(), and limit().")}F.prototype.Pb=function(a,b){A("Query.on",2,4,arguments.length);Da("Query.on",a,n);C("Query.on",2,b,n);var c=Ha("Query.on",arguments[2],arguments[3]);this.k.gb(this,a,b,c.cancel,c.T);return b};F.prototype.on=F.prototype.Pb;
F.prototype.pb=function(a,b,c){A("Query.off",0,3,arguments.length);Da("Query.off",a,l);C("Query.off",2,b,l);sa("Query.off",3,c);this.k.Bb(this,a,b,c)};F.prototype.off=F.prototype.pb;F.prototype.Tc=function(a,b){function c(h){f&&(f=n,e.pb(a,c),b.call(d.T,h))}A("Query.once",2,4,arguments.length);Da("Query.once",a,n);C("Query.once",2,b,n);var d=Ha("Query.once",arguments[2],arguments[3]),e=this,f=l;this.Pb(a,c,function(){e.pb(a,c);d.cancel&&d.cancel.call(d.T)})};F.prototype.once=F.prototype.Tc;
F.prototype.Oc=function(a){A("Query.limit",1,1,arguments.length);(!fa(a)||Math.floor(a)!==a||0>=a)&&g("Query.limit: First argument must be a positive integer.");return new F(this.k,this.path,a,this.W,this.ga,this.la,this.Ea)};F.prototype.limit=F.prototype.Oc;F.prototype.ad=function(a,b){A("Query.startAt",0,2,arguments.length);Ca("Query.startAt",1,a,l);Ea("Query.startAt",b);t(a)||(b=a=m);return new F(this.k,this.path,this.oa,a,b,this.la,this.Ea)};F.prototype.startAt=F.prototype.ad;
F.prototype.Jc=function(a,b){A("Query.endAt",0,2,arguments.length);Ca("Query.endAt",1,a,l);Ea("Query.endAt",b);return new F(this.k,this.path,this.oa,this.W,this.ga,a,b)};F.prototype.endAt=F.prototype.Jc;function Ia(a){var b={};t(a.W)&&(b.sp=a.W);t(a.ga)&&(b.sn=a.ga);t(a.la)&&(b.ep=a.la);t(a.Ea)&&(b.en=a.Ea);t(a.oa)&&(b.l=a.oa);t(a.W)&&(t(a.ga)&&a.W===m&&a.ga===m)&&(b.vf="l");return b}F.prototype.ya=function(){var a=Ja(Ia(this));return"{}"===a?"default":a};
function Ha(a,b,c){var d={};b&&c?(d.cancel=b,C(a,3,d.cancel,l),d.T=c,sa(a,4,d.T)):b&&("object"===typeof b&&b!==m?d.T=b:"function"===typeof b?d.cancel=b:g(Error(B(a,3,l)+"must either be a cancel callback or a context object.")));return d};function I(a){if(a instanceof I)return a;if(1==arguments.length){this.n=a.split("/");for(var b=0,c=0;c<this.n.length;c++)0<this.n[c].length&&(this.n[b]=this.n[c],b++);this.n.length=b;this.U=0}else this.n=arguments[0],this.U=arguments[1]}function E(a){return a.U>=a.n.length?m:a.n[a.U]}function Ma(a){var b=a.U;b<a.n.length&&b++;return new I(a.n,b)}function Na(a){return a.U<a.n.length?a.n[a.n.length-1]:m}r=I.prototype;
r.toString=function(){for(var a="",b=this.U;b<this.n.length;b++)""!==this.n[b]&&(a+="/"+this.n[b]);return a||"/"};r.parent=function(){if(this.U>=this.n.length)return m;for(var a=[],b=this.U;b<this.n.length-1;b++)a.push(this.n[b]);return new I(a,0)};r.B=function(a){for(var b=[],c=this.U;c<this.n.length;c++)b.push(this.n[c]);if(a instanceof I)for(c=a.U;c<a.n.length;c++)b.push(a.n[c]);else{a=a.split("/");for(c=0;c<a.length;c++)0<a[c].length&&b.push(a[c])}return new I(b,0)};
r.f=function(){return this.U>=this.n.length};function Oa(a,b){var c=E(a);if(c===m)return b;if(c===E(b))return Oa(Ma(a),Ma(b));g("INTERNAL ERROR: innerPath ("+b+") is not within outerPath ("+a+")")}r.contains=function(a){var b=0;if(this.n.length>a.n.length)return n;for(;b<this.n.length;){if(this.n[b]!==a.n[b])return n;++b}return l};function Pa(){this.children={};this.Lb=0;this.value=m}function Qa(a,b,c){this.lb=a?a:"";this.Xa=b?b:m;this.u=c?c:new Pa}function J(a,b){for(var c=b instanceof I?b:new I(b),d=a,e;(e=E(c))!==m;)d=new Qa(e,d,ta(d.u.children,e)||new Pa),c=Ma(c);return d}r=Qa.prototype;r.j=function(){return this.u.value};function L(a,b){M("undefined"!==typeof b);a.u.value=b;Ra(a)}r.jb=function(){return 0<this.u.Lb};r.f=function(){return this.j()===m&&!this.jb()};
r.A=function(a){for(var b in this.u.children)a(new Qa(b,this,this.u.children[b]))};function Sa(a,b,c,d){c&&!d&&b(a);a.A(function(a){Sa(a,b,l,d)});c&&d&&b(a)}function Ta(a,b,c){for(a=c?a:a.parent();a!==m;){if(b(a))return l;a=a.parent()}return n}r.path=function(){return new I(this.Xa===m?this.lb:this.Xa.path()+"/"+this.lb)};r.name=aa("lb");r.parent=aa("Xa");
function Ra(a){if(a.Xa!==m){var b=a.Xa,c=a.lb,d=a.f(),e=D(b.u.children,c);d&&e?(delete b.u.children[c],b.u.Lb--,Ra(b)):!d&&!e&&(b.u.children[c]=a.u,b.u.Lb++,Ra(b))}};function N(a,b){this.Ca=a?a:Ua;this.V=b?b:Va}function Ua(a,b){return a<b?-1:a>b?1:0}r=N.prototype;r.ca=function(a,b){return new N(this.Ca,this.V.ca(a,b,this.Ca).copy(m,m,n,m,m))};r.remove=function(a){return new N(this.Ca,this.V.remove(a,this.Ca).copy(m,m,n,m,m))};r.get=function(a){for(var b,c=this.V;!c.f();){b=this.Ca(a,c.key);if(0===b)return c.value;0>b?c=c.left:0<b&&(c=c.right)}return m};
function Wa(a,b){for(var c,d=a.V,e=m;!d.f();){c=a.Ca(b,d.key);if(0===c){if(d.left.f())return e?e.key:m;for(d=d.left;!d.right.f();)d=d.right;return d.key}0>c?d=d.left:0<c&&(e=d,d=d.right)}g("Attempted to find predecessor key for a nonexistent key.  What gives?")}r.f=function(){return this.V.f()};r.count=function(){return this.V.count()};r.Ua=function(){return this.V.Ua()};r.Ha=function(){return this.V.Ha()};r.ma=function(a){return this.V.ma(a)};r.za=function(a){return this.V.za(a)};
r.Fa=function(a){return new Xa(this.V,a)};function Xa(a,b){this.vc=b;for(this.nb=[];!a.f();)this.nb.push(a),a=a.left}function Ya(a){if(0===a.nb.length)return m;var b=a.nb.pop(),c;c=a.vc?a.vc(b.key,b.value):{key:b.key,value:b.value};for(b=b.right;!b.f();)a.nb.push(b),b=b.left;return c}function Za(a,b,c,d,e){this.key=a;this.value=b;this.color=c!=m?c:l;this.left=d!=m?d:Va;this.right=e!=m?e:Va}r=Za.prototype;
r.copy=function(a,b,c,d,e){return new Za(a!=m?a:this.key,b!=m?b:this.value,c!=m?c:this.color,d!=m?d:this.left,e!=m?e:this.right)};r.count=function(){return this.left.count()+1+this.right.count()};r.f=q(n);r.ma=function(a){return this.left.ma(a)||a(this.key,this.value)||this.right.ma(a)};r.za=function(a){return this.right.za(a)||a(this.key,this.value)||this.left.za(a)};function $a(a){return a.left.f()?a:$a(a.left)}r.Ua=function(){return $a(this).key};
r.Ha=function(){return this.right.f()?this.key:this.right.Ha()};r.ca=function(a,b,c){var d,e;e=this;d=c(a,e.key);e=0>d?e.copy(m,m,m,e.left.ca(a,b,c),m):0===d?e.copy(m,b,m,m,m):e.copy(m,m,m,m,e.right.ca(a,b,c));return ab(e)};function bb(a){if(a.left.f())return Va;!a.left.G()&&!a.left.left.G()&&(a=cb(a));a=a.copy(m,m,m,bb(a.left),m);return ab(a)}
r.remove=function(a,b){var c,d;c=this;if(0>b(a,c.key))!c.left.f()&&(!c.left.G()&&!c.left.left.G())&&(c=cb(c)),c=c.copy(m,m,m,c.left.remove(a,b),m);else{c.left.G()&&(c=db(c));!c.right.f()&&(!c.right.G()&&!c.right.left.G())&&(c=eb(c),c.left.left.G()&&(c=db(c),c=eb(c)));if(0===b(a,c.key)){if(c.right.f())return Va;d=$a(c.right);c=c.copy(d.key,d.value,m,m,bb(c.right))}c=c.copy(m,m,m,m,c.right.remove(a,b))}return ab(c)};r.G=aa("color");
function ab(a){a.right.G()&&!a.left.G()&&(a=fb(a));a.left.G()&&a.left.left.G()&&(a=db(a));a.left.G()&&a.right.G()&&(a=eb(a));return a}function cb(a){a=eb(a);a.right.left.G()&&(a=a.copy(m,m,m,m,db(a.right)),a=fb(a),a=eb(a));return a}function fb(a){var b;b=a.copy(m,m,l,m,a.right.left);return a.right.copy(m,m,a.color,b,m)}function db(a){var b;b=a.copy(m,m,l,a.left.right,m);return a.left.copy(m,m,a.color,m,b)}
function eb(a){var b,c;b=a.left.copy(m,m,!a.left.color,m,m);c=a.right.copy(m,m,!a.right.color,m,m);return a.copy(m,m,!a.color,b,c)}function gb(){}r=gb.prototype;r.copy=function(){return this};r.ca=function(a,b){return new Za(a,b,i,i,i)};r.remove=function(){return this};r.get=q(m);r.count=q(0);r.f=q(l);r.ma=q(n);r.za=q(n);r.Ua=q(m);r.Ha=q(m);r.G=q(n);var Va=new gb;var hb=Array.prototype,ib=hb.forEach?function(a,b,c){hb.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=v(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},jb=hb.map?function(a,b,c){return hb.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=v(a)?a.split(""):a,h=0;h<d;h++)h in f&&(e[h]=b.call(c,f[h],h,a));return e};function kb(){};function lb(){this.z=[];this.Kb=[];this.Gc=[];this.ub=[];this.ub[0]=128;for(var a=1;64>a;++a)this.ub[a]=0;this.reset()}ka(lb,kb);lb.prototype.reset=function(){this.z[0]=1732584193;this.z[1]=4023233417;this.z[2]=2562383102;this.z[3]=271733878;this.z[4]=3285377520;this.$b=this.Qa=0};
function mb(a,b){var c;c||(c=0);for(var d=a.Gc,e=c;e<c+64;e+=4)d[e/4]=b[e]<<24|b[e+1]<<16|b[e+2]<<8|b[e+3];for(e=16;80>e;e++){var f=d[e-3]^d[e-8]^d[e-14]^d[e-16];d[e]=(f<<1|f>>>31)&4294967295}c=a.z[0];for(var h=a.z[1],j=a.z[2],k=a.z[3],o=a.z[4],s,e=0;80>e;e++)40>e?20>e?(f=k^h&(j^k),s=1518500249):(f=h^j^k,s=1859775393):60>e?(f=h&j|k&(h|j),s=2400959708):(f=h^j^k,s=3395469782),f=(c<<5|c>>>27)+f+o+s+d[e]&4294967295,o=k,k=j,j=(h<<30|h>>>2)&4294967295,h=c,c=f;a.z[0]=a.z[0]+c&4294967295;a.z[1]=a.z[1]+h&
4294967295;a.z[2]=a.z[2]+j&4294967295;a.z[3]=a.z[3]+k&4294967295;a.z[4]=a.z[4]+o&4294967295}lb.prototype.update=function(a,b){t(b)||(b=a.length);var c=this.Kb,d=this.Qa,e=0;if(v(a))for(;e<b;)c[d++]=a.charCodeAt(e++),64==d&&(mb(this,c),d=0);else for(;e<b;)c[d++]=a[e++],64==d&&(mb(this,c),d=0);this.Qa=d;this.$b+=b};function nb(){this.Ba={};this.length=0}nb.prototype.setItem=function(a,b){D(this.Ba,a)||(this.length+=1);this.Ba[a]=b};nb.prototype.getItem=function(a){return D(this.Ba,a)?this.Ba[a]:m};nb.prototype.removeItem=function(a){D(this.Ba,a)&&(this.length-=1,delete this.Ba[a])};var O=m;if("undefined"!==typeof sessionStorage)try{sessionStorage.setItem("firebase-sentinel","cache"),sessionStorage.removeItem("firebase-sentinel"),O=sessionStorage}catch(ob){O=new nb}else O=new nb;function pb(a,b,c,d){this.host=a;this.Tb=b;this.mb=c;this.na=d||O.getItem(a)||this.host}function qb(a,b){b!==a.na&&(a.na=b,"s-"===a.na.substr(0,2)&&O.setItem(a.host,a.na))}pb.prototype.toString=function(){return(this.Tb?"https://":"http://")+this.host};var rb,sb,tb,ub;function vb(){return ba.navigator?ba.navigator.userAgent:m}ub=tb=sb=rb=n;var wb;if(wb=vb()){var xb=ba.navigator;rb=0==wb.indexOf("Opera");sb=!rb&&-1!=wb.indexOf("MSIE");tb=!rb&&-1!=wb.indexOf("WebKit");ub=!rb&&!tb&&"Gecko"==xb.product}var yb=sb,zb=ub,Ab=tb;var Bb;if(rb&&ba.opera){var Cb=ba.opera.version;"function"==typeof Cb&&Cb()}else zb?Bb=/rv\:([^\);]+)(\)|;)/:yb?Bb=/MSIE\s+([^\);]+)(\)|;)/:Ab&&(Bb=/WebKit\/(\S+)/),Bb&&Bb.exec(vb());var Db=m;var Eb,Fb=1;Eb=function(){return Fb++};function M(a,b){a||g(Error("Firebase INTERNAL ASSERT FAILED:"+b))}
function Gb(a){for(var b=[],c=0,d=0;d<a.length;d++){var e=a.charCodeAt(d);55296<=e&&56319>=e&&(e-=55296,d++,M(d<a.length,"Surrogate pair missing trail surrogate."),e=65536+(e<<10)+(a.charCodeAt(d)-56320));128>e?b[c++]=e:(2048>e?b[c++]=e>>6|192:(65536>e?b[c++]=e>>12|224:(b[c++]=e>>18|240,b[c++]=e>>12&63|128),b[c++]=e>>6&63|128),b[c++]=e&63|128)}a=new lb;a.update(b);b=[];d=8*a.$b;56>a.Qa?a.update(a.ub,56-a.Qa):a.update(a.ub,64-(a.Qa-56));for(c=63;56<=c;c--)a.Kb[c]=d&255,d/=256;mb(a,a.Kb);for(c=d=0;5>
c;c++)for(e=24;0<=e;e-=8)b[d++]=a.z[c]>>e&255;ea(b)||g(Error("encodeByteArray takes an array as a parameter"));if(!Db){Db={};for(a=0;65>a;a++)Db[a]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(a)}a=Db;c=[];for(d=0;d<b.length;d+=3){var f=b[d],h=(e=d+1<b.length)?b[d+1]:0,j=d+2<b.length,k=j?b[d+2]:0,o=f>>2,f=(f&3)<<4|h>>4,h=(h&15)<<2|k>>6,k=k&63;j||(k=64,e||(h=64));c.push(a[o],a[f],a[h],a[k])}return c.join("")}
function Hb(){for(var a="",b=0;b<arguments.length;b++)a=ea(arguments[b])?a+Hb.apply(m,arguments[b]):"object"===typeof arguments[b]?a+z(arguments[b]):a+arguments[b],a+=" ";return a}var Ib=m,Jb=l;function Kb(){Jb===l&&(Jb=n,Ib===m&&"true"===O.getItem("logging_enabled")&&Lb(l));if(Ib){var a=Hb.apply(m,arguments);Ib(a)}}function Mb(a){return function(){Kb(a,arguments)}}
function Nb(){if("undefined"!==typeof console){var a="FIREBASE INTERNAL ERROR: "+Hb.apply(m,arguments);"undefined"!==typeof console.error?console.error(a):console.log(a)}}function Pb(){var a=Hb.apply(m,arguments);g(Error("FIREBASE FATAL ERROR: "+a))}function P(){if("undefined"!==typeof console){var a="FIREBASE WARNING: "+Hb.apply(m,arguments);"undefined"!==typeof console.warn?console.warn(a):console.log(a)}}
function Ba(a){return fa(a)&&(a!=a||a==Number.POSITIVE_INFINITY||a==Number.NEGATIVE_INFINITY)}function Qb(a,b){return a!==b?a===m?-1:b===m?1:typeof a!==typeof b?"number"===typeof a?-1:1:a>b?1:-1:0}function Rb(a,b){if(b&&a in b)return b[a];g(Error("Missing required key ("+a+") in object: "+z(b)))}var Sb=0;function Ja(a){if("object"!==typeof a||a===m)return z(a);var b=[],c;for(c in a)b.push(c);b.sort();c="{";for(var d=0;d<b.length;d++)0!==d&&(c+=","),c+=z(b[d]),c+=":",c+=Ja(a[b[d]]);return c+"}"}
function Tb(a){M(!Ba(a));var b,c,d,e;0===a?(d=c=0,b=-Infinity===1/a?1:0):(b=0>a,a=Math.abs(a),a>=Math.pow(2,-1022)?(d=Math.min(Math.floor(Math.log(a)/Math.LN2),1023),c=d+1023,d=Math.round(a*Math.pow(2,52-d)-Math.pow(2,52))):(c=0,d=Math.round(a/Math.pow(2,-1074))));e=[];for(a=52;a;a-=1)e.push(d%2?1:0),d=Math.floor(d/2);for(a=11;a;a-=1)e.push(c%2?1:0),c=Math.floor(c/2);e.push(b?1:0);e.reverse();b=e.join("");c="";for(a=0;64>a;a+=8)d=parseInt(b.substr(a,8),2).toString(16),1===d.length&&(d="0"+d),c+=d;
return c.toLowerCase()};function Ub(a,b){this.ja=a;M(this.ja!==m,"LeafNode shouldn't be created with null value.");this.Ia="undefined"!==typeof b?b:m}r=Ub.prototype;r.J=q(l);r.m=aa("Ia");r.Jb=function(a){return new Ub(this.ja,a)};r.M=function(){return Q};r.D=function(a){return E(a)===m?this:Q};r.Q=q(m);r.C=function(a,b){return(new R(new N,this.Ia)).C(a,b)};r.Ma=function(a,b){var c=E(a);return c===m?b:this.C(c,Q.Ma(Ma(a),b))};r.f=q(n);r.ob=q(0);
r.X=function(a){return a&&this.m()!==m?{".value":this.j(),".priority":this.m()}:this.j()};r.hash=function(){var a="";this.m()!==m&&(a+="priority:"+Vb(this.m())+":");var b=typeof this.ja,a=a+(b+":"),a="number"===b?a+Tb(this.ja):a+this.ja;return Gb(a)};r.j=aa("ja");r.toString=function(){return"string"===typeof this.ja?'"'+this.ja+'"':this.ja};function R(a,b){this.P=a||new N;this.Ia="undefined"!==typeof b?b:m}r=R.prototype;r.J=q(n);r.m=aa("Ia");r.Jb=function(a){return new R(this.P,a)};r.C=function(a,b){var c=this.P.remove(a);b&&b.f()&&(b=m);b!==m&&(c=c.ca(a,b));return b&&b.m()!==m?new Wb(c,m,this.Ia):new R(c,this.Ia)};r.Ma=function(a,b){var c=E(a);if(c===m)return b;var d=this.M(c).Ma(Ma(a),b);return this.C(c,d)};r.f=function(){return this.P.f()};r.ob=function(){return this.P.count()};var Xb=/^\d+$/;r=R.prototype;
r.X=function(a){if(this.f())return m;var b={},c=0,d=0,e=l;this.A(function(f,h){b[f]=h.X(a);c++;e&&Xb.test(f)?d=Math.max(d,Number(f)):e=n});if(!a&&e&&d<2*c){var f=[],h;for(h in b)f[h]=b[h];return f}a&&this.m()!==m&&(b[".priority"]=this.m());return b};r.hash=function(){var a="";this.m()!==m&&(a+="priority:"+Vb(this.m())+":");this.A(function(b,c){var d=c.hash();""!==d&&(a+=":"+b+":"+d)});return""===a?"":Gb(a)};r.M=function(a){a=this.P.get(a);return a===m?Q:a};
r.D=function(a){var b=E(a);return b===m?this:this.M(b).D(Ma(a))};r.Q=function(a){return Wa(this.P,a)};r.jc=function(){return this.P.Ua()};r.kc=function(){return this.P.Ha()};r.A=function(a){return this.P.ma(a)};r.Mb=function(a){return this.P.za(a)};r.Fa=function(){return this.P.Fa()};r.toString=function(){var a="{",b=l;this.A(function(c,d){b?b=n:a+=", ";a+='"'+c+'" : '+d.toString()});return a+="}"};var Q=new R(new N);function Wb(a,b,c){R.call(this,a,c);b===m&&(b=new N(Yb),a.ma(function(a,c){b=b.ca({name:a,pa:c.m()},c)}));this.fa=b}ka(Wb,R);r=Wb.prototype;r.C=function(a,b){var c=this.M(a),d=this.P,e=this.fa;c!==m&&(d=d.remove(a),e=e.remove({name:a,pa:c.m()}));b&&b.f()&&(b=m);b!==m&&(d=d.ca(a,b),e=e.ca({name:a,pa:b.m()},b));return new Wb(d,e,this.m())};r.Q=function(a,b){var c=Wa(this.fa,{name:a,pa:b.m()});return c?c.name:m};r.A=function(a){return this.fa.ma(function(b,c){return a(b.name,c)})};
r.Mb=function(a){return this.fa.za(function(b,c){return a(b.name,c)})};r.Fa=function(){return this.fa.Fa(function(a,b){return{key:a.name,value:b}})};r.jc=function(){return this.fa.f()?m:this.fa.Ua().name};r.kc=function(){return this.fa.f()?m:this.fa.Ha().name};function Zb(a,b){if("object"!==typeof a)return new Ub(a,b);if(a===m)return Q;var c=m;".priority"in a?c=a[".priority"]:"undefined"!==typeof b&&(c=b);M(c===m||"string"===typeof c||"number"===typeof c);if(".value"in a&&a[".value"]!==m)return new Ub(a[".value"],c);var c=new R(new N,c),d;for(d in a)if(D(a,d)&&"."!==d.substring(0,1)){var e=Zb(a[d]);if(e.J()||!e.f())c=c.C(d,e)}return c}function Yb(a,b){return Qb(a.pa,b.pa)||(a.name!==b.name?a.name<b.name?-1:1:0)}
function Vb(a){return"number"===typeof a?"number:"+Tb(a):"string:"+a};function S(a,b){this.u=a;this.Ab=b}S.prototype.X=function(){A("Firebase.DataSnapshot.val",0,0,arguments.length);return this.u.X()};S.prototype.val=S.prototype.X;S.prototype.Kc=function(){A("Firebase.DataSnapshot.exportVal",0,0,arguments.length);return this.u.X(l)};S.prototype.exportVal=S.prototype.Kc;S.prototype.B=function(a){A("Firebase.DataSnapshot.child",0,1,arguments.length);fa(a)&&(a=String(a));Fa("Firebase.DataSnapshot.child",a);var b=new I(a),c=this.Ab.B(b);return new S(this.u.D(b),c)};
S.prototype.child=S.prototype.B;S.prototype.Nb=function(a){A("Firebase.DataSnapshot.hasChild",1,1,arguments.length);Fa("Firebase.DataSnapshot.hasChild",a);var b=new I(a);return!this.u.D(b).f()};S.prototype.hasChild=S.prototype.Nb;S.prototype.m=function(){A("Firebase.DataSnapshot.getPriority",0,0,arguments.length);return this.u.m()};S.prototype.getPriority=S.prototype.m;
S.prototype.forEach=function(a){A("Firebase.DataSnapshot.forEach",1,1,arguments.length);C("Firebase.DataSnapshot.forEach",1,a,n);if(this.u.J())return n;var b=this;return this.u.A(function(c,d){return a(new S(d,b.Ab.B(c)))})};S.prototype.forEach=S.prototype.forEach;S.prototype.jb=function(){A("Firebase.DataSnapshot.hasChildren",0,0,arguments.length);return this.u.J()?n:!this.u.f()};S.prototype.hasChildren=S.prototype.jb;
S.prototype.name=function(){A("Firebase.DataSnapshot.name",0,0,arguments.length);return this.Ab.name()};S.prototype.name=S.prototype.name;S.prototype.ob=function(){A("Firebase.DataSnapshot.numChildren",0,0,arguments.length);return this.u.ob()};S.prototype.numChildren=S.prototype.ob;S.prototype.Uc=function(){A("Firebase.DataSnapshot.ref",0,0,arguments.length);return this.Ab};S.prototype.ref=S.prototype.Uc;function T(a,b){for(var c in a)b.call(i,a[c],c,a)}function $b(a){var b={},c;for(c in a)b[c]=a[c];return b};function ac(){this.Oa={}}function bc(a,b,c){t(c)||(c=1);D(a.Oa,b)||(a.Oa[b]=0);a.Oa[b]+=c}ac.prototype.get=function(){return $b(this.Oa)};function cc(a){this.Hc=a;this.kb=m}cc.prototype.get=function(){var a=this.Hc.get(),b=$b(a);if(this.kb)for(var c in this.kb)b[c]-=this.kb[c];this.kb=a;return b};function dc(a,b){this.Yb={};this.Fb=new cc(a);this.o=b;setTimeout(y(this.tc,this),10+6E4*Math.random())}dc.prototype.tc=function(){var a=this.Fb.get(),b={},c=n,d;for(d in a)0<a[d]&&D(this.Yb,d)&&(b[d]=a[d],c=l);c&&(a=this.o,a.Y&&(b={c:b},a.e("reportStats",b),a.ra("s",b)));setTimeout(y(this.tc,this),6E5*Math.random())};var ec={},fc={};function gc(a){a=a.toString();ec[a]||(ec[a]=new ac);return ec[a]};var hc=m;"undefined"!==typeof MozWebSocket?hc=MozWebSocket:"undefined"!==typeof WebSocket&&(hc=WebSocket);function ic(a,b,c){this.cc=a;this.e=Mb(this.cc);this.frames=this.Sa=m;this.Zb=0;this.ta=gc(b);this.Da=(b.Tb?"wss://":"ws://")+b.na+"/.ws?v=5";b.host!==b.na&&(this.Da=this.Da+"&ns="+b.mb);c&&(this.Da=this.Da+"&s="+c)}var jc;
ic.prototype.open=function(a,b){this.da=b;this.sb=a;this.e("websocket connecting to "+this.Da);this.R=new hc(this.Da);this.gc=n;var c=this;this.R.onopen=function(){c.e("Websocket connected.");c.gc=l};this.R.onclose=function(){c.e("Websocket connection was disconnected.");c.R=m;kc(c)};this.R.onmessage=function(a){if(c.R!==m)if(a=a.data,bc(c.ta,"bytes_received",a.length),c.frames!==m)lc(c,a);else{a:{M(c.frames===m,"We already have a frame buffer");if(4>=a.length){var b=Number(a);if(!isNaN(b)){c.Zb=
b;c.frames=[];a=m;break a}}c.Zb=1;c.frames=[]}a!==m&&lc(c,a)}};this.R.onerror=function(){c.e("WebSocket error.  Closing connection.");kc(c)}};ic.prototype.start=p();ic.isAvailable=function(){return!("undefined"!==typeof navigator&&"Opera"===navigator.appName)&&hc!==m&&!jc};function lc(a,b){a.frames.push(b);if(a.frames.length==a.Zb){var c=a.frames.join("");a.frames=m;c="undefined"!==typeof JSON&&t(JSON.parse)?JSON.parse(c):la(c);mc(a);a.sb(c)}}
ic.prototype.send=function(a){mc(this);a=z(a);bc(this.ta,"bytes_sent",a.length);if(16384>=a.length)a=[a];else{for(var b=[],c=0;c<a.length;c+=16384)c+16384>a?b.push(a.substring(c,a.length)):b.push(a.substring(c,c+16384));a=b}1<a.length&&this.R.send(String(a.length));for(b=0;b<a.length;b++)this.R.send(a[b])};function nc(a){a.nc=l;a.Sa&&(clearTimeout(a.Sa),a.Sa=m);a.R&&(a.R.close(),a.R=m)}function kc(a){a.nc||(a.e("WebSocket is closing itself"),nc(a),a.da&&(a.da(a.gc),a.da=m))}
ic.prototype.close=function(){this.nc||(this.e("WebSocket is being closed"),nc(this))};function mc(a){clearTimeout(a.Sa);a.Sa=setInterval(function(){a.R.send("0");mc(a)},45E3)};function oc(){this.set={}}r=oc.prototype;r.add=function(a,b){this.set[a]=b!==m?b:l};r.contains=function(a){return D(this.set,a)};r.get=function(a){return this.set[a]};r.remove=function(a){delete this.set[a]};r.f=function(){var a;a:{for(a in this.set){a=n;break a}a=l}return a};r.count=function(){var a=0,b;for(b in this.set)a++;return a};r.keys=function(){var a=[],b;for(b in this.set)D(this.set,b)&&a.push(b);return a};function pc(){function a(a,c){c&&c.isAvailable()&&b.push(c)}var b=[],c=qc;if("array"==da(c))for(var d=0;d<c.length;++d)a(0,c[d]);else T(c,a);this.Hb=b}var qc=[ic];function U(a,b,c,d,e,f){this.id=a;this.e=Mb("c:"+this.id+":");this.Sc=c;this.Va=d;this.xa=e;this.Sb=f;this.L=b;this.vb=[];this.dc=0;this.ac=new pc;this.ha=0;this.e("Connection created");rc(this)}function rc(a){var b;var c=a.ac;0<c.Hb.length?b=c.Hb[0]:g(Error("No transports available"));a.I=new b("c:"+a.id+":"+a.dc++,a.L);b=sc(a,a.I);c=tc(a,a.I);a.eb=a.I;a.cb=a.I;a.I.open(b,c);a.w=m}
function tc(a,b){return function(c){b===a.I?(a.I=m,!c&&0===a.ha?(a.e("Realtime connection failed."),"s-"===a.L.na.substr(0,2)&&(O.removeItem(a.L.mb),a.L.na=a.L.host)):1===a.ha&&a.e("Realtime connection lost."),a.close()):b===a.w?(c=a.w,a.w=m,(a.eb===c||a.cb===c)&&a.close()):a.e("closing an old connection")}}
function sc(a,b){return function(c){if(2!=a.ha)if(b===a.cb){var d=Rb("t",c),c=Rb("d",c);if("c"==d){if(d=Rb("t",c),"d"in c)if(c=c.d,"h"===d){var d=c.ts,e=c.v,f=c.h;a.Yc=c.s;qb(a.L,f);if(0==a.ha&&(a.I.start(),c=a.I,a.e("Realtime connection established."),a.I=c,a.ha=1,a.Va&&(a.Va(d),a.Va=m),"5"!==e&&P("Protocol version mismatch detected"),c=1<a.ac.Hb.length?a.ac.Hb[1]:m))a.w=new c("c:"+a.id+":"+a.dc++,a.L,a.Yc),a.w.open(sc(a,a.w),tc(a,a.w))}else if("n"===d){a.e("recvd end transmission on primary");a.cb=
a.w;for(c=0;c<a.vb.length;++c)a.qb(a.vb[c]);a.vb=[];uc(a)}else"s"===d?(a.e("Connection shutdown command received. Shutting down..."),a.Sb&&(a.Sb(c),a.Sb=m),a.xa=m,a.close()):"r"===d?(a.e("Reset packet received.  New host: "+c),qb(a.L,c),1===a.ha?a.close():(vc(a),rc(a))):Nb("Unknown control packet command: "+d)}else"d"==d&&a.qb(c)}else b===a.w?(d=Rb("t",c),c=Rb("d",c),"c"==d?"t"in c&&(c=c.t,"a"===c?(a.w.start(),a.e("sending client ack on secondary"),a.w.send({t:"c",d:{t:"a",d:{}}}),a.e("Ending transmission on primary"),
a.I.send({t:"c",d:{t:"n",d:{}}}),a.eb=a.w,uc(a)):"r"===c&&(a.e("Got a reset on secondary, closing it"),a.w.close(),(a.eb===a.w||a.cb===a.w)&&a.close())):"d"==d?a.vb.push(c):g(Error("Unknown protocol layer: "+d))):a.e("message on old connection")}}U.prototype.Vb=function(a){a={t:"d",d:a};1!==this.ha&&g("Connection is not connected");this.eb.send(a)};function uc(a){a.eb===a.w&&a.cb===a.w&&(a.e("cleaning up and promoting a connection: "+a.w.cc),a.I=a.w,a.w=m)}U.prototype.qb=function(a){this.Sc(a)};
U.prototype.close=function(){2!==this.ha&&(this.e("Closing realtime connection."),this.ha=2,vc(this),this.xa&&(this.xa(),this.xa=m))};function vc(a){a.e("Shutting down all connections");a.I&&(a.I.close(),a.I=m);a.w&&(a.w.close(),a.w=m)};function wc(a,b,c,d){this.id=xc++;this.e=Mb("p:"+this.id+":");this.La=l;this.Z={};this.N=[];this.Wa=0;this.Rb={};this.Y=n;this.zb=1E3;this.rb=b;this.qc=c;this.xa=d;this.L=a;this.Ub=m;this.wb=[];this.qa={};this.Xc=0;this.Ta=this.oc=m;setTimeout(y(this.ec,this),0)}var xc=0,yc=0;r=wc.prototype;
r.ra=function(a,b,c,d){var e=++this.Xc,a={r:e,a:a,b:b};this.e(z(a));this.Y?this.ab.Vb(a):this.wb.push(a);var f=this,a=setTimeout(function(){var a=f.qa[e];a&&(delete f.qa[e],a.ba&&a.ba.tb&&a.ba.tb())},45E3);this.qa[e]={ba:{sb:c,tb:d},Ac:a}};function zc(a,b,c,d,e){a.e("Listen on "+b+" for "+c);var f={p:b},d=jb(d,function(a){return Ia(a)});"{}"!==c&&(f.q=d);a.ra("l",f,function(d){a.e("listen response",d);d=d.s;"ok"!==d&&Ac(a,b,c);e&&e(d)},function(){a.e("timed out on listen...")})}
r.Na=function(a,b){this.hb={Ic:a,hc:n,$:b};this.e("Authenticating using credential: "+this.hb);Bc(this)};r.fb=function(){delete this.hb;this.Y&&this.ra("unauth",{},p(),p())};function Bc(a){var b=a.hb;a.Y&&b&&a.ra("auth",{cred:b.Ic},function(c){c=c.s;"ok"!==c&&delete a.hb;b.hc||(b.hc=l,b.$&&b.$(c))},function(){a.e("timed out on auth...")})}
r.Cc=function(a,b,c){a=a.toString();if(Ac(this,a,b)&&this.Y){this.e("Unlisten on "+a+" for "+b);var d=this,a={p:a},c=jb(c,function(a){return Ia(a)});"{}"!==b&&(a.q=c);this.ra("u",a,m,function(){d.e("timed out on unlisten...")})}};r.da=function(a,b){this.Rb[a]=b;this.Y&&Cc(this,a,b)};function Cc(a,b,c){b={p:b,d:c};a.e("onDisconnect",b);a.ra("o",b,function(a){"ok"!==a.s&&g("onDisconnect failed: "+z(a.d))},function(){a.e("timed out on onDisconnect...")})}r.put=function(a,b,c,d){Dc(this,"p",a,b,c,d)};
function Dc(a,b,c,d,e,f){c={p:c,d:d};t(f)&&(c.h=f);a.N.push({action:b,uc:c,F:e});a.Wa++;b=a.N.length-1;a.Y&&Ec(a,b)}function Ec(a,b){var c=a.N[b].action,d=a.N[b].F;a.ra(c,a.N[b].uc,function(e){a.e(c+" response",e);delete a.N[b];a.Wa--;0===a.Wa&&(a.N=[]);d&&d(e.s)},function(){a.e("timed out on put...")})}
r.qb=function(a){if("r"in a){this.e("from server: "+z(a));var b=a.r,c=this.qa[b];c&&(delete this.qa[b],clearTimeout(c.Ac),c.ba&&c.ba.sb&&c.ba.sb(a.b))}else"error"in a&&g("A server-side error has occurred: "+a.error),"a"in a&&(b=a.a,c=a.b,this.e("handleServerMessage",b,c),"d"===b?this.rb(c.p,c.d):"m"===b?this.rb(c.p,c.d,l):"c"===b?(a=c.p,b=(b=c.q)?jb(b,function(a){return Ja(a)}).join("$"):"{}",(a=Ac(this,a,b))&&a.F&&a.F("permission_denied")):"sd"===b?this.Ub?this.Ub(c):"msg"in c&&"undefined"!==typeof console&&
console.log("FIREBASE: "+c.msg.replace("\n","\nFIREBASE: ")):Nb("Unrecognized action received from server: "+z(b)+"\nAre you using the latest client?"))};
r.Va=function(a){this.e("connection ready");this.Y=l;this.Ta=(new Date).getTime();Sb=a-(new Date).getTime();for(a=0;a<this.wb.length;a++)this.ab.Vb(this.wb[a]);this.wb=[];Bc(this);for(var b in this.Z)for(var c in this.Z[b])a=this.Z[b][c],zc(this,b,c,a.Ja,a.F);for(b in this.Rb)Cc(this,b,this.Rb[b]);for(b=0;b<this.N.length;b++)this.N[b]&&Ec(this,b);this.qc&&this.qc()};
r.rc=function(){this.Y=n;this.e("data client disconnected");if(!this.La){for(var a=0;a<this.N.length;a++){var b=this.N[a];b&&"h"in b.uc&&(b.F&&b.F("disconnect"),delete this.N[a],this.Wa--)}0===this.Wa&&(this.N=[]);for(var c in this.qa)a=this.qa[c],delete this.qa[c],a!==m&&(a.ba&&a.ba.tb&&a.ba.tb(),clearTimeout(a.Ac))}var d=y(function(){this.ec()},this);this.La?(this.Ta&&(3E4<(new Date).getTime()-this.Ta&&(this.zb=1E3),this.Ta=m),c=Math.max(0,this.zb-((new Date).getTime()-this.oc)),c*=Math.random(),
this.e("Trying to reconnect in "+c+"ms"),setTimeout(d,c),this.zb=Math.min(3E4,1.3*this.zb)):this.wc=function(){setTimeout(d,0)};this.xa&&this.xa()};r.ec=function(){if(this.La){this.e("Making a connection attempt");this.oc=(new Date).getTime();this.Ta=m;var a=y(this.qb,this),b=y(this.Va,this),c=y(this.rc,this),d=this.id+":"+yc++,e=this;this.ab=new U(d,this.L,a,b,c,function(a){e.La=n;g(Error(a))})}};r.Ga=function(){this.La=n;this.ab?this.ab.close():this.rc()};
r.bb=function(){this.La=l;this.wc();this.wc=i};function Ac(a,b,c){b=(new I(b)).toString();c||(c="{}");var d=a.Z[b][c];delete a.Z[b][c];return d};function Fc(){this.Aa=Q}function V(a,b){return a.Aa.D(b)}function W(a,b,c){a.Aa=a.Aa.Ma(b,c)}Fc.prototype.toString=function(){return this.Aa.toString()};function Gc(){this.sa=new Fc;this.K=new Fc;this.ua=new Fc;this.Za=new Qa}function Hc(a,b){for(var c=V(a.sa,b),d=V(a.K,b),e=J(a.Za,b),f=n,h=e;h!==m;){if(h.j()!==m){f=l;break}h=h.parent()}if(f)return n;c=Ic(c,d,e);return c!==d?(W(a.K,b,c),l):n}function Ic(a,b,c){if(c.f())return a;if(c.j()!==m)return b;a=a||Q;c.A(function(d){var d=d.name(),e=a.M(d),f=b.M(d),h=J(c,d),e=Ic(e,f,h);a=a.C(d,e)});return a}
Gc.prototype.set=function(a,b){var c=this,d=[];ib(b,function(a){var b=a.path,a=a.wa,h=Eb();L(J(c.Za,b),h);W(c.K,b,a);d.push({path:b,Zc:h})});return d};function Jc(a,b){ib(b,function(b){var d=b.Zc,b=J(a.Za,b.path),e=b.j();M(e!==m,"pendingPut should not be null.");e===d&&L(b,m)})};function Kc(){this.va=[]}function Lc(a,b){if(0!==b.length){a.va.push.apply(a.va,b);for(var c=0;c<a.va.length;c++)if(a.va[c]){var d=a.va[c];a.va[c]=m;var e=d.$;e(d.yc,d.$a)}a.va=[]}};function X(a,b,c,d){this.type=a;this.ea=b;this.S=c;this.$a=d};function Mc(a){this.H=a;this.aa=[];this.fc=new Kc}function Nc(a,b,c,d,e){a.aa.push({type:b,$:c,cancel:d,T:e});var d=[],f=Oc(a.g);a.Ra&&f.push(new X("value",a.g));for(var h=0;h<f.length;h++)if(f[h].type===b){var j=new Y(a.H.k,a.H.path);f[h].S&&(j=j.B(f[h].S));d.push({$:e?y(c,e):c,yc:new S(f[h].ea,j),$a:f[h].$a})}Lc(a.fc,d)}Mc.prototype.xb=function(a,b){b=this.yb(a,b);b!=m&&Pc(this,b)};
function Pc(a,b){for(var c=[],d=0;d<b.length;d++){var e=b[d],f=e.type,h=new Y(a.H.k,a.H.path);b[d].S&&(h=h.B(b[d].S));h=new S(b[d].ea,h);"value"===e.type&&!h.jb()?f+="("+h.X()+")":"value"!==e.type&&(f+=" "+h.name());Kb(a.H.k.o.id+": event:"+a.H.path+":"+a.H.ya()+":"+f);for(f=0;f<a.aa.length;f++){var j=a.aa[f];b[d].type===j.type&&c.push({$:j.T?y(j.$,j.T):j.$,yc:h,$a:e.$a})}}Lc(a.fc,c)}function Oc(a){var b=[];if(!a.J()){var c=m;a.A(function(a,e){b.push(new X("child_added",e,a,c));c=a})}return b}
function Qc(a){a.Ra||(a.Ra=l,Pc(a,[new X("value",a.g)]))};function Rc(a,b){Mc.call(this,a);this.g=b}ka(Rc,Mc);Rc.prototype.yb=function(a,b){this.g=a;this.Ra&&b!=m&&b.push(new X("value",this.g));return b};Rc.prototype.Pa=function(){return{}};function Sc(a,b){this.ib=a;this.Qb=b}
function Tc(a,b,c,d,e){var f=a.D(c),h=b.D(c),d=new Sc(d,e),e=Uc(d,c,f,h),j=n;if(!f.f()&&!h.f()&&f.m()!==h.m())var j=a.D(c.parent()),k=b.D(c.parent()),o=Na(c),j=j.Q(o,f)!=k.Q(o,h);if(e||j){f=c;c=e;for(h=j;f.parent()!==m;){var s=a.D(f),e=b.D(f),j=f.parent();if(!d.ib||J(d.ib,j).j())k=b.D(j),o=[],f=Na(f),s.f()?(s=k.Q(f,e),o.push(new X("child_added",e,f,s))):e.f()?o.push(new X("child_removed",s,f)):(s=k.Q(f,e),h&&o.push(new X("child_moved",e,f,s)),c&&o.push(new X("child_changed",e,f,s))),d.Qb(j,k,o);h&&
(h=n,c=l);f=j}}}function Uc(a,b,c,d){var e,f=[];c===d?e=n:c.J()&&d.J()?e=c.j()!==d.j():c.J()?(Vc(a,b,Q,d,f),e=l):d.J()?(Vc(a,b,c,Q,f),e=l):e=Vc(a,b,c,d,f);e?a.Qb(b,d,f):c.m()!==d.m()&&a.Qb(b,d,m);return e}
function Vc(a,b,c,d,e){var f=n,h=!a.ib||!J(a.ib,b).f(),j=[],k=[],o=[],s=[],x={},u={},w,K,H,G;w=c.Fa();H=Ya(w);K=d.Fa();for(G=Ya(K);H!==m||G!==m;){c=H===m?1:G===m?-1:H.key===G.key?0:Yb({name:H.key,pa:H.value.m()},{name:G.key,pa:G.value.m()});if(0>c)f=ta(x,H.key),t(f)?(o.push({ic:H,Bc:j[f]}),j[f]=m):(u[H.key]=k.length,k.push(H)),f=l,H=Ya(w);else{if(0<c)f=ta(u,G.key),t(f)?(o.push({ic:k[f],Bc:G}),k[f]=m):(x[G.key]=j.length,j.push(G)),f=l;else{c=b.B(G.key);if(c=Uc(a,c,H.value,G.value))s.push(G),f=l;H=
Ya(w)}G=Ya(K)}if(!h&&f)return l}for(h=0;h<k.length;h++)if(x=k[h])c=b.B(x.key),Uc(a,c,x.value,Q),e.push(new X("child_removed",x.value,x.key));for(h=0;h<j.length;h++)if(x=j[h])c=b.B(x.key),k=d.Q(x.key,x.value),Uc(a,c,Q,x.value),e.push(new X("child_added",x.value,x.key,k));for(h=0;h<o.length;h++)x=o[h].ic,j=o[h].Bc,c=b.B(j.key),k=d.Q(j.key,j.value),e.push(new X("child_moved",j.value,j.key,k)),(c=Uc(a,c,x.value,j.value))&&s.push(j);for(h=0;h<s.length;h++)a=s[h],k=d.Q(a.key,a.value),e.push(new X("child_changed",
a.value,a.key,k));return f};function Wc(){this.Ya=this.ia=m;this.set={}}ka(Wc,oc);r=Wc.prototype;r.setActive=function(a){this.ia=a};function Zc(a){return a.contains("default")}function $c(a){return a.ia!=m&&Zc(a)}r.defaultView=function(){return Zc(this)?this.get("default"):m};r.path=aa("Ya");r.toString=function(){return jb(this.keys(),function(a){return"default"===a?"{}":a}).join("$")};r.Ja=function(){var a=[];T(this.set,function(b){a.push(b.H)});return a};function ad(a,b){Mc.call(this,a);this.g=Q;this.yb(b,Oc(b))}ka(ad,Mc);
ad.prototype.yb=function(a,b){if(b===m)return b;var c=[],d=this.H;t(d.W)&&(t(d.ga)&&d.ga!=m?c.push(function(a,b){var c=Qb(b,d.W);return 0<c||0===c&&a>=d.ga}):c.push(function(a,b){return 0<=Qb(b,d.W)}));t(d.la)&&(t(d.Ea)?c.push(function(a,b){var c=Qb(b,d.la);return 0>c||0===c&&a<=d.Ea}):c.push(function(a,b){return 0>=Qb(b,d.la)}));var e=m,f=m;if(t(this.H.oa))if(t(this.H.W)){if(e=bd(a,c,this.H.oa,n)){var h=a.M(e).m();c.push(function(a,b){var c=Qb(b,h);return 0>c||0===c&&a<=e})}}else if(f=bd(a,c,this.H.oa,
l)){var j=a.M(f).m();c.push(function(a,b){var c=Qb(b,j);return 0<c||0===c&&a>=f})}for(var k=[],o=[],s=[],x=[],u=0;u<b.length;u++){var w=b[u].S,K=b[u].ea;switch(b[u].type){case "child_added":cd(c,w,K)&&(this.g=this.g.C(w,K),o.push(b[u]));break;case "child_removed":this.g.M(w).f()||(this.g=this.g.C(w,m),k.push(b[u]));break;case "child_changed":!this.g.M(w).f()&&cd(c,w,K)&&(this.g=this.g.C(w,K),x.push(b[u]));break;case "child_moved":var H=!this.g.M(w).f(),G=cd(c,w,K);H?G?(this.g=this.g.C(w,K),s.push(b[u])):
(k.push(new X("child_removed",this.g.M(w),w)),this.g=this.g.C(w,m)):G&&(this.g=this.g.C(w,K),o.push(b[u]))}}var Xc=e||f;if(Xc){var Yc=(u=f!==m)?this.g.jc():this.g.kc(),Ob=n,Ka=n,La=this;(u?a.Mb:a.A).call(a,function(a,b){!Ka&&Yc===m&&(Ka=l);if(Ka&&Ob)return l;Ob?(k.push(new X("child_removed",La.g.M(a),a)),La.g=La.g.C(a,m)):Ka&&(o.push(new X("child_added",b,a)),La.g=La.g.C(a,b));Yc===a&&(Ka=l);a===Xc&&(Ob=l)})}for(u=0;u<o.length;u++)c=o[u],w=this.g.Q(c.S,c.ea),k.push(new X("child_added",c.ea,c.S,w));
for(u=0;u<s.length;u++)c=s[u],w=this.g.Q(c.S,c.ea),k.push(new X("child_moved",c.ea,c.S,w));for(u=0;u<x.length;u++)c=x[u],w=this.g.Q(c.S,c.ea),k.push(new X("child_changed",c.ea,c.S,w));this.Ra&&0<k.length&&k.push(new X("value",this.g));return k};function bd(a,b,c,d){if(a.J())return m;var e=m;(d?a.Mb:a.A).call(a,function(a,d){if(cd(b,a,d)&&(e=a,c--,0===c))return l});return e}function cd(a,b,c){for(var d=0;d<a.length;d++)if(!a[d](b,c.m()))return n;return l}
ad.prototype.Nb=function(a){return this.g.M(a)!==Q};ad.prototype.Pa=function(a,b,c){var d={};this.g.J()||this.g.A(function(a){d[a]=l});var e=this.g,c=V(c,new I("")),f=new Qa;L(J(f,this.H.path),l);var h=Q.Ma(a,b),j=[];Tc(c,h,a,f,function(a,b,c){c!==m&&(j=j.concat(c))});this.yb(b,j);this.g.J()||this.g.A(function(a){d[a]=l});this.g=e;return d};function dd(a,b){this.o=a;this.i=b;this.pc=b.Aa;this.ka=new Qa}
dd.prototype.gb=function(a,b,c,d,e){var f=a.path,h=J(this.ka,f),j=h.j();j===m?(j=new Wc,L(h,j)):M(!j.f(),"We shouldn't be storing empty QueryMaps");var k=a.ya();if(j.contains(k))Nc(j.get(k),b,c,d,e);else{var o=this.i.Aa.D(f),a="default"===a.ya()?new Rc(a,o):new ad(a,o);if($c(j)||ed(h))j.add(k,a),j.Ya||(j.Ya=a.H.path);else{var s,x;j.f()||(s=j.toString(),x=j.Ja());j.add(k,a);j.Ya||(j.Ya=a.H.path);j.setActive(fd(this,j));s&&x&&this.o.Cc(j.path(),s,x)}$c(j)&&Sa(h,function(a){if(a=a.j()){a.ia&&a.ia();
a.ia=m}});Nc(a,b,c,d,e);(b=(b=Ta(J(this.ka,f),function(a){var b;if(b=a.j())if(b=a.j().defaultView())b=a.j().defaultView().Ra;if(b)return l},l))||this.o===m)&&Qc(a)}};function gd(a,b,c,d,e){for(var f=a.get(b),h=n,j=f.aa.length-1;0<=j;j--){var k=f.aa[j];if((!c||k.type===c)&&(!d||k.$===d)&&(!e||k.T===e))if(f.aa.splice(j,1),h=l,c&&d)break}(c=h&&!(0<f.aa.length))&&a.remove(b);return c}dd.prototype.Bb=function(a,b,c,d){var e=J(this.ka,a.path).j();return e===m?m:hd(this,e,a,b,c,d)};
function hd(a,b,c,d,e,f){var h=b.path(),h=J(a.ka,h),c=c?c.ya():m,j=[];c&&"default"!==c?gd(b,c,d,e,f)&&j.push(c):ib(b.keys(),function(a){gd(b,a,d,e,f)&&j.push(a)});b.f()&&L(h,m);c=ed(h);if(0<j.length&&!c){for(var k=h,o=h.parent(),c=n;!c&&o;){var s=o.j();if(s){M(!$c(s));var x=k.name(),u=n;T(s.set,function(a){u=a.Nb(x)||u});u&&(c=l)}k=o;o=o.parent()}k=m;if(!$c(b)){o=b.ia;b.ia=m;var w=[],K=function(b){var c=b.j();c&&Zc(c)?(w.push(c.path()),c.ia==m&&c.setActive(fd(a,c))):(c&&c.ia==m&&c.setActive(fd(a,
c)),b.A(K))};K(h);k=w;o&&o()}return c?m:k}return m}function id(a,b,c){Sa(J(a.ka,b),function(a){(a=a.j())&&T(a.set,function(a){Qc(a)})},c,l)}function jd(a,b,c){function d(a){for(var b=0;b<c.length;++b)if(c[b].contains(a))return l;return n}var e=a.pc,f=a.i.Aa;a.pc=f;var h=b.toString();Tc(e,f,b,a.ka,function(b,c,e){if(b.toString().substring(0,h.length)===h){var f=d(b);f&&id(a,b,n);a.xb(b,c,e);f&&id(a,b,l)}else a.xb(b,c,e)});d(b)&&id(a,b,l)}
dd.prototype.xb=function(a,b,c){a=J(this.ka,a).j();a!==m&&T(a.set,function(a){a.xb(b,c)})};function ed(a){return Ta(a,function(a){return a.j()&&$c(a.j())})}
function fd(a,b){if(a.o){var c=b.keys(),d=a.o,e=function(d){"ok"!==d?(P("on() or once() for "+b.path().toString()+" failed: "+d),b&&T(b.set,function(a){for(var b=0;b<a.aa.length;b++){var c=a.aa[b];c.cancel&&(c.T?y(c.cancel,c.T):c.cancel)()}}),hd(a,b)):ib(c,function(a){(a=b.get(a))&&Qc(a)})},f=b.toString(),h=b.path().toString();d.Z[h]=d.Z[h]||{};M(!d.Z[h][f],"listen() called twice for same path/queryId.");d.Z[h][f]={Ja:b.Ja(),F:e};d.Y&&zc(d,h,f,b.Ja(),e);return y(a.o.Cc,a.o,b.path(),b.toString(),b.Ja())}return ca}
dd.prototype.Pa=function(a,b,c,d){var e={};T(b.set,function(b){b=b.Pa(a,c,d);T(b,function(a,b){e[b]=D(e,b)?e:a})});c.J()||c.A(function(a){D(e,a)||(e[a]=n)});return e};function kd(a,b,c,d,e,f){var h=b.path();if(f!==m){var j=[];d.J()||d.A(function(a,b){j.push({path:h.B(a),wa:b});delete f[a]});T(f,function(a,b){j.push({path:h.B(b),wa:Q})});return j}var b=a.Pa(h,b,d,e),k=Q,o=[];T(b,function(b,f){var h=new I(f);b?k=k.C(f,d.D(h)):o=o.concat(ld(a,d.D(h),J(c,h),e))});return[{path:h,wa:k}].concat(o)}
function md(a,b,c,d,e){for(var f=J(a.ka,b),h=f.parent(),j=n;!j&&h!==m;){var k=h.j();k!==m&&(Zc(k)?j=l:(k=a.Pa(b,k,c,d),f=f.name(),ta(k,f)&&(j=l)));f=h;h=h.parent()}if(j)return[{path:b,wa:c}];h=J(a.ka,b);j=h.j();return j!==m?Zc(j)?[{path:b,wa:c}]:kd(a,j,h,c,d,e):ld(a,c,h,d)}function ld(a,b,c,d){var e=c.j();if(e!==m)return Zc(e)?[{path:c.path(),wa:b}]:kd(a,e,c,b,d,m);if(b.J())return[];var f=[];b.A(function(b,e){var k=new I(b);f=f.concat(ld(a,e,J(c,k),d))});return f};function nd(a){this.L=a;this.ta=gc(a);this.o=new wc(this.L,y(this.rb,this),y(this.Qc,this),y(this.Rc,this));var b=y(function(){return new dc(this.ta,this.o)},this),a=a.toString();fc[a]||(fc[a]=b());this.zc=fc[a];this.Gb=new Qa;this.i=new Gc;this.O=new dd(this.o,this.i.ua);this.lc=new Fc;this.Ob=new dd(m,this.lc);od(this,n)}r=nd.prototype;r.toString=function(){return(this.L.Tb?"https://":"http://")+this.L.host};r.name=function(){return this.L.mb};
r.rb=function(a,b,c){var d=[],e=m;if(9<=a.length&&a.lastIndexOf(".priority")===a.length-9)a=new I(a.substring(0,a.length-9)),c=V(this.i.sa,a).Jb(b),d.push(a);else if(c){var e=b,a=new I(a),c=V(this.i.sa,a),f;for(f in b){var h=Zb(b[f]),c=c.C(f,h);d.push(a.B(f))}}else a=new I(a),c=Zb(b),d.push(a);b=md(this.O,a,c,this.i.K,e);e=n;for(f=0;f<b.length;++f){var c=b[f],h=this.i,j=c.path;W(h.sa,j,c.wa);e=Hc(h,j)||e}e&&(a=pd(this,a),qd(this,a),a=a.path());jd(this.O,a,d)};r.Qc=function(){od(this,l)};
r.Rc=function(){od(this,n)};function od(a,b){var c=new I("/.info/connected");W(a.lc,c,Zb(b));jd(a.Ob,c,[c])}r.Na=function(a,b){this.o.Na(a,function(a){rd(b,"ok"===a,a)})};r.fb=function(){this.o.fb()};
r.Eb=function(a,b,c,d){this.e("set",{path:a.toString(),value:b});var b=Zb(b,c),c=md(this.O,a,b,this.i.K,m),e=this.i.set(a,c),f=this;this.o.put(a.toString(),b.X(l),function(b){var c="ok"===b;Jc(f.i,e);if(!c){P("set at "+a+" failed: "+b);Hc(f.i,a);var k=pd(f,a);qd(f,k);jd(f.O,k.path(),[])}rd(d,c,b)});b=pd(this,a);sd(this,a);qd(this,b);jd(this.O,b.path(),[a])};
r.update=function(a,b,c){this.e("update",{path:a.toString(),value:b});var d=V(this.i.ua,a),e=l,f=[],h;for(h in b){var e=n,j=Zb(b[h]),d=d.C(h,j);f.push(a.B(h))}if(e)Kb("update() called with empty data.  Don't do anything."),rd(c,l);else{var d=md(this.O,a,d,this.i.K,b),k=this.i.set(a,d),o=this;Dc(this.o,"m",a.toString(),b,function(b){M("ok"===b||"permission_denied"===b,"merge at "+a+" failed.");var d="ok"===b;Jc(o.i,k);rd(c,d,b)},i);b=pd(this,a);sd(this,a);qd(this,b);jd(this.O,b.path(),f)}};
r.Wb=function(a,b,c){this.e("setPriority",{path:a.toString(),pa:b});var d=V(this.i.K,a).Jb(b),d=md(this.O,a,d,this.i.K,m),e=this.i.set(a,d),f=this;this.o.put(a.toString()+"/.priority",b,function(a){var b="ok"===a;Jc(f.i,e);rd(c,b,a)});a=pd(this,a);qd(this,a);jd(this.O,a.path(),[])};r.Db=function(a,b){this.o.da(a.toString(),b)};r.gb=function(a,b,c,d,e){".info"===E(a.path)?this.Ob.gb(a,b,c,d,e):this.O.gb(a,b,c,d,e)};
r.Bb=function(a,b,c,d){if(".info"===E(a.path))this.Ob.Bb(a,b,c,d);else if(b=this.O.Bb(a,b,c,d),b!==m){for(var c=this.i,a=a.path,d=[],e=0;e<b.length;++e)d[e]=V(c.sa,b[e]);W(c.sa,a,Q);for(e=0;e<b.length;++e)W(c.sa,b[e],d[e])}};r.Ga=function(){this.o.Ga()};r.bb=function(){this.o.bb()};
r.Xb=function(a){if("undefined"!==typeof console){a?(this.Fb||(this.Fb=new cc(this.ta)),a=this.Fb.get()):a=this.ta.get();var b=a,c=[],d=0,e;for(e in b)c[d++]=e;var f=function(a,b){return Math.max(b.length,a)};if(c.reduce)e=c.reduce(f,0);else{var h=0;ib(c,function(a){h=f.call(i,h,a)});e=h}for(var j in a){b=a[j];for(c=j.length;c<e+2;c++)j+=" ";console.log(j+b)}}};r.e=function(){Kb("r:"+this.o.id+":",arguments)};function td(a,b){var c=new Y(a,b);return new S(V(a.i.ua,b),c)}
function rd(a,b,c){a&&(1===a.length?a(b):b?a(m):a(Error(c)))}
function ud(a,b,c){ga(c)&&1===c.length&&(P("\n"+b+' was passed an onComplete callback that takes 1 argument.\nOn 2/4/2013, we are changing our callback signature from:\n    function(success) { /* success is true for success, false for failure. */ }\nto:\n    function(error) { /* error is null for success, an Error object for failure. */ }\n\nTHIS WILL BE A BREAKING CHANGE!  To fix your code, you can either:\n * Remove all parameters from your callback. E.g.:\n     function() { ... }\n * Opt in to the new behavior early by adding a "dummy" second argument. E.g.:\n     function(error, dummy) { ... }\nPlease email support@firebase.com for more info.'),bc(a.ta,
"old_callback"),a.zc.Yb.old_callback=l)};function sd(a,b){var c=J(a.Gb,b);Ta(c,function(b){vd(a,b)});vd(a,c);Sa(c,function(b){vd(a,b)})}function vd(a,b){var c=b.j();if(c!==m){for(var d=-1,e=[],f=0;f<c.length;f++)if(2===c[f].status)M(d===f-1,"All SENT items should be at beginning of queue."),d=f,c[f].status=4,c[f].bc="set";else if(c[f].Ib(),c[f].F){var h=td(a,b.path());e.push(wd(c[f].F,Error("set"),n,h))}-1===d?L(b,m):c.length=d+1;for(f=0;f<e.length;f++)e[f]()}}
function xd(a,b){var c=b||a.Gb;b||yd(a,c);if(!c.f())if(c.j()!==m){var d=zd(a,c);if(0!==d.length){var e=c.path();if(2!==d[0].status&&4!==d[0].status){for(var f=0;f<d.length;f++)M(1===d[f].status,"tryToSendTransactionForNode_: items in queue should all be run."),d[f].status=2,d[f].xc++;var h=V(a.i.K,e).hash();W(a.i.K,e,V(a.i.ua,e));var j=V(a.i.K,e).X(l),k=Eb();L(J(a.i.Za,e),k);a.o.put(e.toString(),j,function(b){a.e("transaction put response",{path:e.toString(),status:b});var h=J(a.i.Za,e),j=h.j();M(j!==
m,"tryToSendTransactionsForNode_: pendingPut should not be null.");j===k&&(L(h,m),W(a.i.K,e,V(a.i.sa,e)));if("ok"===b){b=[];for(f=0;f<d.length;f++)d[f].status=3,d[f].F&&(h=td(a,d[f].path),b.push(wd(d[f].F,m,l,h))),d[f].Ib();yd(a,c);xd(a);for(f=0;f<b.length;f++)b[f]()}else{if("datastale"===b)for(f=0;f<d.length;f++)d[f].status=4===d[f].status?5:1;else{P("transaction at "+e+" failed: "+b);for(f=0;f<d.length;f++)d[f].status=5,d[f].bc=b}b=pd(a,e);qd(a,b);jd(a.O,b.path(),[e])}},h)}}}else c.A(function(b){xd(a,
b)})}
function qd(a,b){var c=b.path();W(a.i.ua,c,V(a.i.K,c));var d=zd(a,b);if(0!==d.length){for(var e=V(a.i.ua,c),f=[],h=0;h<d.length;h++){var j=Oa(c,d[h].path),k=n,o;M(j!==m,"rerunTransactionsUnderNode_: relativePath should not be null.");if(5===d[h].status)k=l,o=d[h].bc;else if(1===d[h].status)if(25<=d[h].xc)k=l,o="maxretry";else{var s=d[h].update(e.D(j).X());t(s)?(za("transaction failed: Data returned ",s),e=e.Ma(j,Zb(s))):(k=l,o="nodata")}k&&(d[h].Ib(),d[h].status=3,d[h].F&&(k=new Y(a,d[h].path),j=
new S(e.D(j),k),"nodata"===o?f.push(wd(d[h].F,m,n,j)):f.push(wd(d[h].F,Error(o),n,j))))}d=V(a.i.K,c).m();W(a.i.ua,c,e.Jb(d));xd(a);for(h=0;h<f.length;h++)f[h]()}}function pd(a,b){for(var c,d=a.Gb;(c=E(b))!==m&&d.j()===m;)d=J(d,c),b=Ma(b);return d}function zd(a,b){var c=[];Ad(a,b,c);c.sort(function(a,b){return a.sc-b.sc});return c}function Ad(a,b,c){var d=b.j();if(d!==m)for(var e=0;e<d.length;e++)c.push(d[e]);b.A(function(b){Ad(a,b,c)})}
function yd(a,b){var c=b.j();if(c){for(var d=0,e=0;e<c.length;e++)3!==c[e].status&&(c[d]=c[e],d++);c.length=d;L(b,0<c.length?c:m)}b.A(function(b){yd(a,b)})}function wd(a,b,c,d){return!a?p():0<a.length&&4>a.length?function(){a(c,d,b===m?"":b.message)}:function(){a(b,c,d)}};function Z(){this.Ka={}}Z.Mc=function(){return Z.mc?Z.mc:Z.mc=new Z};Z.prototype.Ga=function(){for(var a in this.Ka)this.Ka[a].Ga()};Z.prototype.interrupt=Z.prototype.Ga;Z.prototype.bb=function(){for(var a in this.Ka)this.Ka[a].bb()};Z.prototype.resume=Z.prototype.bb;var $={Nc:function(a){var b=R.prototype.hash;R.prototype.hash=a;return function(){R.prototype.hash=b}}};$.hijackHash=$.Nc;$.ya=function(a){return a.ya()};$.queryIdentifier=$.ya;$.Pc=function(a){return a.k.o.Z};$.listens=$.Pc;$.Vc=function(a){return a.k.o.ab};$.refConnection=$.Vc;$.Ec=wc;$.DataConnection=$.Ec;wc.prototype.sendRequest=wc.prototype.ra;wc.prototype.interrupt=wc.prototype.Ga;$.Fc=U;$.RealTimeConnection=$.Fc;U.prototype.sendRequest=U.prototype.Vb;U.prototype.close=U.prototype.close;
$.Dc=pb;$.ConnectionTarget=$.Dc;$.Lc=function(){jc=l};$.forceLongPolling=$.Lc;$.$c=function(a,b){a.k.o.Ub=b};$.setSecurityDebugCallback=$.$c;$.Xb=function(a,b){a.k.Xb(b)};$.stats=$.Xb;var Bd,Cd=0,Dd=[];Bd=function(){var a=(new Date).getTime()+Sb,b=a===Cd;Cd=a;for(var c=Array(8),d=7;0<=d;d--)c[d]="-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz".charAt(a%64),a=Math.floor(a/64);M(0===a);a=c.join("");if(b){for(d=11;0<=d&&63===Dd[d];d--)Dd[d]=0;Dd[d]++}else for(d=0;12>d;d++)Dd[d]=Math.floor(64*Math.random());for(d=0;12>d;d++)a+="-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz".charAt(Dd[d]);M(20===a.length,"NextPushId: Length should be 20.");return a};function Y(){var a,b,c;if(arguments[0]instanceof nd)c=arguments[0],a=arguments[1];else{A("new Firebase",1,2,arguments.length);var d=arguments[0],e="";a="";b=l;var f="";if(v(d)){e=d.indexOf("//");0<=e&&(b="http:"!==d.substring(0,e),d=d.substring(e+2));var h=d.indexOf("/");-1===h&&(h=d.length);e=d.substring(0,h);d=d.substring(h+1);h=e.split(".");if(3==h.length){if("firebase"===h[1])Pb(e+" is no longer supported. Please use <YOUR FIREBASE>.firebaseio.com instead");else{a=h[0];f="";d=("/"+d).split("/");
for(h=0;h<d.length;h++)if(0<d[h].length){var j=d[h];try{j=decodeURIComponent(j.replace(/\+/g," "))}catch(k){}f+="/"+j}}a=a.toLowerCase()}else a=m}b||"undefined"!==typeof window&&(window.location&&window.location.protocol&&-1!==window.location.protocol.indexOf("https:"))&&P("Insecure Firebase access from a secure page. Please use https in calls to new Firebase().");a=new pb(e,b,a);b=new I(f);e=b.toString();if(!(d=!v(a.host)))if(!(d=0===a.host.length))if(!(d=!xa(a.mb)))if(d=0!==e.length)e&&(e=e.replace(/^\/*\.info(\/|$)/,
"/")),d=!(v(e)&&0!==e.length&&!wa.test(e));d&&g(Error(B("new Firebase",1,n)+'must be a valid firebase URL and the path can\'t contain ".", "#", "$", "[", or "]".'));arguments[1]?arguments[1]instanceof Z?c=arguments[1]:g(Error("Expected a valid Firebase.Context for second argument to new Firebase()")):c=Z.Mc();e=a.toString();d=ta(c.Ka,e);d||(d=new nd(a),c.Ka[e]=d);c=d;a=b}F.call(this,c,a)}ka(Y,F);var Ed=Y,Fd=["Firebase"],Gd=ba;!(Fd[0]in Gd)&&Gd.execScript&&Gd.execScript("var "+Fd[0]);
for(var Hd;Fd.length&&(Hd=Fd.shift());)!Fd.length&&t(Ed)?Gd[Hd]=Ed:Gd=Gd[Hd]?Gd[Hd]:Gd[Hd]={};Y.prototype.name=function(){A("Firebase.name",0,0,arguments.length);return this.path.f()?m:Na(this.path)};Y.prototype.name=Y.prototype.name;Y.prototype.B=function(a){A("Firebase.child",1,1,arguments.length);if(fa(a))a=String(a);else if(!(a instanceof I))if(E(this.path)===m){var b=a;b&&(b=b.replace(/^\/*\.info(\/|$)/,"/"));Fa("Firebase.child",b)}else Fa("Firebase.child",a);return new Y(this.k,this.path.B(a))};
Y.prototype.child=Y.prototype.B;Y.prototype.parent=function(){A("Firebase.parent",0,0,arguments.length);var a=this.path.parent();return a===m?m:new Y(this.k,a)};Y.prototype.parent=Y.prototype.parent;Y.prototype.toString=function(){A("Firebase.toString",0,0,arguments.length);var a;if(this.parent()===m)a=this.k.toString();else{a=this.parent().toString()+"/";var b=this.name();a+=encodeURIComponent(String(b))}return a};Y.prototype.toString=Y.prototype.toString;
Y.prototype.set=function(a,b){A("Firebase.set",1,2,arguments.length);Ga("Firebase.set",this.path);ya("Firebase.set",a,n);C("Firebase.set",2,b,l);ud(this.k,"Firebase.set",b);return this.k.Eb(this.path,a,m,b)};Y.prototype.set=Y.prototype.set;
Y.prototype.update=function(a,b){A("Firebase.update",1,2,arguments.length);Ga("Firebase.update",this.path);ha(a)||g(Error(B("Firebase.update",1,n)+" must be an object containing the children to replace."));ya("Firebase.update",a,n);C("Firebase.update",2,b,l);ud(this.k,"Firebase.update",b);return this.k.update(this.path,a,b)};Y.prototype.update=Y.prototype.update;
Y.prototype.Eb=function(a,b,c){A("Firebase.setWithPriority",2,3,arguments.length);Ga("Firebase.setWithPriority",this.path);ya("Firebase.setWithPriority",a,n);Ca("Firebase.setWithPriority",2,b,n);C("Firebase.setWithPriority",3,c,l);ud(this.k,"Firebase.setWithPriority",c);(".length"===this.name()||".keys"===this.name())&&g("Firebase.setWithPriority failed: "+this.name()+" is a read-only object.");return this.k.Eb(this.path,a,b,c)};Y.prototype.setWithPriority=Y.prototype.Eb;
Y.prototype.remove=function(a){A("Firebase.remove",0,1,arguments.length);Ga("Firebase.remove",this.path);C("Firebase.remove",1,a,l);ud(this.k,"Firebase.remove",a);this.set(m,a)};Y.prototype.remove=Y.prototype.remove;
Y.prototype.transaction=function(a,b){function c(){}A("Firebase.transaction",1,2,arguments.length);Ga("Firebase.transaction",this.path);C("Firebase.transaction",1,a,n);C("Firebase.transaction",2,b,l);var d=this.k;ga(b)&&(0<b.length&&4>b.length)&&(P("\nFirebase.transaction was passed an onComplete callback that takes "+b.length+' arguments.\nOn 2/4/2013, we are changing our transaction callback signature from:\n    function(success, snapshot, abortReason) {\n        // success is true if the transaction was committed, false for any failure.\n    }\nto:\n    function(error, committed, snapshot) { \n        // error is an Error object on fatal errors, else null.\n        // committed is true if the transaction was committed, false if you returned no data from your update function.\n    }\n\nTHIS WILL BE A BREAKING CHANGE!  To fix your code, you can either:\n * Remove all parameters from your callback. E.g.:\n   function() { ... }\n * Opt in to the new behavior early by adding a 4th "dummy" argument. E.g.:\n   function(error, committed, snapshot, dummy) { ... }\nPlease email support@firebase.com for more info.'),
bc(d.ta,"old_callback_transaction"),d.zc.Yb.old_callback_transaction=l);(".length"===this.name()||".keys"===this.name())&&g("Firebase.transaction failed: "+this.name()+" is a read-only object.");var e=this.k,f=this.path;e.e("transaction on "+f);var h=new Y(e,f);h.Pb("value",c);var d={path:f,update:a,F:b,sc:Eb(),xc:0,Ib:function(){h.pb("value",c)}},j=e.i.ua,k=d.update(V(j,f).X());if(t(k)){za("transaction failed: Data returned ",k);var o=V(e.i.K,f).m();W(j,f,Zb(k,o));jd(e.O,f,[f]);d.status=1;f=J(e.Gb,
f);j=f.j()||[];j.push(d);L(f,j);xd(e)}else d.Ib(),d.F&&(e=td(e,f),wd(d.F,m,n,e)())};Y.prototype.transaction=Y.prototype.transaction;Y.prototype.Wb=function(a,b){A("Firebase.setPriority",1,2,arguments.length);Ga("Firebase.setPriority",this.path);Ca("Firebase.setPriority",1,a,n);C("Firebase.setPriority",2,b,l);ud(this.k,"Firebase.setPriority",b);this.k.Wb(this.path,a,b)};Y.prototype.setPriority=Y.prototype.Wb;
Y.prototype.push=function(a,b){A("Firebase.push",0,2,arguments.length);Ga("Firebase.push",this.path);ya("Firebase.push",a,l);C("Firebase.push",2,b,l);ud(this.k,"Firebase.push",b);var c=Bd(),c=this.B(c);"undefined"!==typeof a&&a!==m&&c.set(a,b);return c};Y.prototype.push=Y.prototype.push;Y.prototype.da=function(){var a=this;return{set:function(b){a.k.Db(a.path,b)},setWithPriority:p(),setPriority:p(),remove:function(){a.k.Db(a.path,m)},update:p(),cancel:p()}};Y.prototype.onDisconnect=Y.prototype.da;
Y.prototype.Wc=function(){A("Firebase.removeOnDisconnect",0,0,arguments.length);P("FirebaseRef.removeOnDisconnect() being deprecated. Please use FirebaseRef.onDisconnect().remove() instead.");this.da().remove()};Y.prototype.removeOnDisconnect=Y.prototype.Wc;Y.prototype.Db=function(a){A("Firebase.setOnDisconnect",1,1,arguments.length);ya("Firebase.setOnDisconnect",a,n);P("FirebaseRef.setOnDisconnect(value) being deprecated. Please use FirebaseRef.onDisconnect().set(value) instead.");this.da().set(a)};
Y.prototype.setOnDisconnect=Y.prototype.Db;Y.prototype.Na=function(a,b){A("Firebase.auth",1,2,arguments.length);v(a)||g(Error(B("Firebase.auth",1,n)+"must be a valid credential (a string)."));C("Firebase.auth",2,b,l);ud(this.k,"Firebase.auth",b);this.k.Na(a,b)};Y.prototype.auth=Y.prototype.Na;Y.prototype.fb=function(){this.k.fb()};Y.prototype.unauth=Y.prototype.fb;
function Lb(a,b){M(!b||a===l||a===n,"Can't turn on custom loggers persistently.");a===l?("undefined"!==typeof console&&("function"===typeof console.log?Ib=y(console.log,console):"object"===typeof console.log&&(Ib=function(a){console.log(a)})),b&&O.setItem("logging_enabled","true")):a?Ib=a:(Ib=m,O.removeItem("logging_enabled"))}Y.enableLogging=Lb;Y.INTERNAL=$;Y.Context=Z;})();
exports.Firebase = Firebase;